### ISSUE TITLE
editProfile.js using placeholder

### ISSUE THREAD

**Issue by danjohnvelasco** [AxelAlba/Obscura_V2#11]
.val() is more appropriate than placeholder since the attribute "value" is the one being submitted. While the placeholder is used for hints.

**Comment by AxelAlba** [comment]
I used placeholder instead of val since it is expected for the user to input a new value. Kaya may if else statements sa editProfile.js since if merong ininput yung user sa editProfile use that, pero pag wala, use the place holder instead since yun yung initial value.

P.S.
Suggestion mo ba dito is wag na mag place holder tapos mag lagay nalang ng "initial" value?

**Comment by AxelAlba** [comment]
Pero yep, if gawin ko ngang value instead of placeholder, di ko na need mag if else.. Thank you.
